# Generated by Django 4.0.4 on 2022-04-19 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('cnic', models.IntegerField(verbose_name='CNIC #')),
                ('contact_number', models.IntegerField(verbose_name='Contact #')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, verbose_name='Gender')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farmer Profile',
                'verbose_name_plural': 'Farmer Profiles',
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntn', models.IntegerField(verbose_name='NTN #')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('office_contact_number', models.IntegerField(verbose_name='Contact #')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compnay_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profiles',
            },
        ),
        migrations.CreateModel(
            name='CompanyOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('cnic', models.IntegerField(verbose_name='CNIC #')),
                ('contact_number', models.IntegerField(verbose_name='Contact #')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, verbose_name='Gender')),
                ('compnay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compnay_owner', to='users.companyprofile')),
            ],
            options={
                'verbose_name': 'Company Owner',
                'verbose_name_plural': 'Company Owners',
            },
        ),
        migrations.CreateModel(
            name='CompanyManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('cnic', models.IntegerField(verbose_name='CNIC #')),
                ('contact_number', models.IntegerField(verbose_name='Contact #')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, verbose_name='Gender')),
                ('compnay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compnay_manager', to='users.companyprofile')),
            ],
            options={
                'verbose_name': 'Company Manager',
                'verbose_name_plural': 'Company Managers',
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('cnic', models.IntegerField(verbose_name='CNIC #')),
                ('contact_number', models.IntegerField(verbose_name='Contact #')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, verbose_name='Gender')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Profile',
                'verbose_name_plural': 'Admin Profiles',
            },
        ),
    ]
